# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('conteudo', models.TextField(max_length=1500)),
                ('data', models.DateField()),
                ('imagem', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breadtimesite.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breadtimesite.TipoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='ViewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contviews', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breadtimesite.Usuario'),
        ),
        migrations.AddField(
            model_name='post',
            name='viewsPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breadtimesite.ViewsPost'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set([('desc',)]),
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together=set([('nome',)]),
        ),
    ]
