# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadtimesite', '0002_auto_20160809_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='static/img/upload'),
        ),
    ]
