# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadtimesite', '0002_auto_20160808_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contview',
            field=models.IntegerField(),
        ),
    ]
