# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadtimesite', '0003_auto_20160727_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='breadtimesite/static/img/upload'),
        ),
    ]
