# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadtimesite', '0005_auto_20160809_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
