# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadtimesite', '0006_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
