# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadtimesite', '0007_auto_20160810_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
