# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadtimesite', '0008_auto_20160819_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='static/img/uploads'),
        ),
    ]
